apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrawatch.fullname" . }}-backend
  labels:
    {{- include "infrawatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.services.backend.replicas }}
  selector:
    matchLabels:
      {{- include "infrawatch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "infrawatch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "infrawatch.serviceAccountName" . }}
      containers:
        - name: backend
          image: "{{ .Values.services.backend.image.repository }}:{{ .Values.services.backend.image.tag }}"
          imagePullPolicy: {{ .Values.services.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.aws.existingSecret | default (include "infrawatch.fullname" .) }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            {{- toYaml .Values.services.backend.resources | nindent 12 }}
