{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "infrawatch.fullname" . }}
  labels:
    {{- include "infrawatch.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.certManager.enabled }}
    {{- if eq .Values.ingress.certManager.issuerType "ClusterIssuer" }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.issuerName }}
    {{- else }}
    cert-manager.io/issuer: {{ .Values.ingress.certManager.issuerName }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.certManager.enabled }}
  tls:
    {{- if .Values.ingress.certManager.enabled }}
    {{- range .Values.ingress.hosts }}
    - secretName: {{ .host | replace "." "-" }}-tls
      hosts:
        - {{ .host | quote }}
    {{- end }}
    {{- else }}
    {{- toYaml .Values.ingress.tls | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "infrawatch.fullname" $ }}-backend
                port:
                  number: 8000
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "infrawatch.fullname" $ }}-frontend
                port:
                  number: 8080
          {{- end }}
    {{- end }}
{{- end }}
